<!DOCTYPE HTML>
<html>
	<head>
		<meta charset="utf-8">
		<title>Cetak Kartu</title>
		<link rel="stylesheet" href="/resources/css/card.css" type="text/css" />
		<script type="text/javascript" src="/resources/js/jquery.min"></script>
		<script type="text/javascript" src="/resources/js/jspdf/jspdf.js"></script>
	</head>
	<body>

		<div id="content">
			<h3>KSP SIKOPAWI MANDIRI, Purwakarta</h3>
			<p>Kartu Piutang</p>

			<div id="detail-left">
				<table>
					<tr>
						<td class="strong">No. Rekening</td>
						<td>:</td>
						<td><?php echo $this->data['DEBITUR_NO_REK']?></td>
					</tr>
					<tr>
						<td class="strong">Plafond</td>
						<td>:</td>
						<td>Rp <?php echo number_format($this->data['PERMOHONAN_KREDIT_PLAFOND'])?> ,-</td>
					</tr>
					<tr>
						<td class="strong">Jangka Waktu</td>
						<td>:</td>
						<td><?php echo $this->data['PERMOHONAN_KREDIT_JWAKTU']?> Bulan</td>
					</tr>
					<tr>
						<td class="strong">Bunga</td>
						<td>:</td>
						<td>Rp <?php echo number_format($this->data['PERMOHONAN_KREDIT_BUNGA'])?> ,-</td>
					</tr>
					<tr>
						<td class="strong">Angsuran</td>
						<td>:</td>
						<td>Rp <?php echo number_format($this->data['PERMOHONAN_KREDIT_ANGSURAN'])?> ,-</td>
					</tr>
				</table>
			</div>

			<div id="detail-left" style="margin-left: 20px">
				<table>
					<tr>
						<td class="strong">Nama</td>
						<td>:</td>
						<td><?php echo $this->data['CUSTOMERS_NAME']?></td>
					</tr>
					<tr>
						<td class="strong">Alamat</td>
						<td>:</td>
						<td><?php echo $this->data['CUSTOMERS_ADDRESS']?></td>
					</tr>
					<tr>
						<td class="strong">Kategori Debitur</td>
						<td>:</td>
						<td><?php echo $this->data['DEBITUR_CATEGORY_NAME']?></td>
					</tr>
					<tr>
						<td class="strong">Kategori Kredit</td>
						<td>:</td>
						<td><?php echo $this->data['KREDIT_CATEGORY_NAME']?></td>
					</tr>
					<tr>
						<td class="strong">Payment Point</td>
						<td>:</td>
						<td><?php echo $this->data['PAYMENT_POINT_NAME']?></td>
					</tr>
				</table>
			</div>

			<div id="detail-left" style="margin-left: 20px">
				<table>
					<tr>
						<td class="strong">Status</td>
						<td>:</td>
						<td><?php echo $this->data['STATUS']?></td>
					</tr>
				</table>
			</div>

			<br clear="all" />

			<table style="width: 100%" class="table" cellspacing="0" cellpadding="0">
				<tr>
					<th>No</th>
					<th>Tanggal</th>
					<th>Baki Awal</th>
					<th>Pokok</th>
					<th>Bunga</th>
					<th>Jumlah</th>
					<th>Pokok</th>
					<th>Bunga</th>
					<th>Jumlah</th>
					<th>Baki Akhir</th>
				</tr>
				<?php foreach($this->paymentData as $k=>$d): ?>
				<tr>
					<td <?php echo ($k%2>0) ? 'class="grey"' : ''?>align="center"><?php echo $d['PAYMENT_ID']?></td>
					<td <?php echo ($k%2>0) ? 'class="grey"' : ''?>align="center"><?php echo $d['TANGGAL']?></td>
					<td <?php echo ($k%2>0) ? 'class="grey"' : ''?>align="center">Rp <?php echo number_format($d['BAKI_AWAL']) ?></td>
					<td <?php echo ($k%2>0) ? 'class="grey"' : ''?>align="right">Rp <?php echo number_format($d['ATD_POKOK']) ?></td>
					<td <?php echo ($k%2>0) ? 'class="grey"' : ''?>align="right">Rp <?php echo number_format($d['ATD_BUNGA']) ?></td>
					<td <?php echo ($k%2>0) ? 'class="grey"' : ''?>align="right">Rp <?php echo number_format($d['ATD_JUMLAH']) ?></td>
					<td <?php echo ($k%2>0) ? 'class="grey"' : ''?>align="right">Rp <?php echo number_format($d['AJT_POKOK']) ?></td>
					<td <?php echo ($k%2>0) ? 'class="grey"' : ''?>align="right">Rp <?php echo number_format($d['AJT_BUNGA']) ?></td>
					<td <?php echo ($k%2>0) ? 'class="grey"' : ''?>align="right">Rp <?php echo number_format($d['AJT_JUMLAH']) ?></td>
					<td <?php echo ($k%2>0) ? 'class="grey"' : ''?>align="right">Rp <?php echo number_format($d['BAKI_AKHIR']) ?></td>
				</tr>
				<?php endforeach; ?>
			</table>
		</div>

	</body>
</html>