<!DOCTYPE HTML>
<html>
	<head>
		<meta charset="utf-8">
		<title>MyProject</title>
		<!-- Start : CSS -->
		<link rel="stylesheet" href="<?php echo $this->baseUrl('resources/css/extjs4.2.1/css/ext-all.css')?>" type="text/css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl('resources/css/style.css')?>" type="text/css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl('resources/css/icons.css')?>" type="text/css" />
		<!-- End of : CSS -->
		<!-- Start : JS -->
		<script type="text/javascript" src="<?php echo $this->baseUrl('resources/js/extjs4.2.1/ext-all-dev.js')?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('assets/js/MyIndo.js')?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('assets/js/MyProject.js')?>"></script>
		<script type="text/javascript">
			MyIndo.setBaseUrl('<?php echo $this->baseUrl('')?>');
			MyIndo.setSiteUrl('<?php echo $this->url()?>');
			MyIndo.setNameSpace('MyProject');
			MyIndo.setUsername('<?php echo $this->username?>');
			MyIndo.setName('<?php echo $this->fname?> <?php echo $this->lname?>');
			// MyIndo.data.customer.lastNoReg = '<?php echo $this->customerLastId;?>';
		</script>
		<!-- End of : JS -->
	</head>
	<body>
		<?php echo $this->layout()->content . "\n"; ?>
	</body>
</html>